rtl8188eu-objs :=		\
		dm.o		\
		hw.o		\
		led.o		\
		phy.o		\
		rf.o		\
		fw.o		\
		sw.o		\
		table.o		\
		pwrseq.o		\
		trx.o

obj-$(CONFIG_RTL8188EU) += rtl8188eu.o

ccflags-y += -D__CHECK_ENDIAN__
